global:
  scrape_interval: 15s
  external_labels:
    monitor: 'railway-prom'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:${PORT}']

  - job_name: 'railway-backend'
    static_configs:
      - targets: ['${BACKEND_URL}']
    metrics_path: '/metrics/metrics'
    scheme: https
    scrape_interval: 15s
    scrape_timeout: 10s